# Generated by Django 4.0.4 on 2022-05-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
    ]
